# Generated by Django 4.2.5 on 2023-10-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('transactionId', models.CharField(auto_created=True, max_length=20, unique=True)),
                ('id', models.CharField(auto_created=True, max_length=20, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=122)),
                ('monument', models.CharField(max_length=122)),
                ('ticketCount', models.IntegerField()),
                ('ticketPrice', models.CharField(max_length=10)),
                ('totalPrice', models.CharField(max_length=10)),
                ('time', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('scanned', models.BooleanField(default=False)),
            ],
        ),
    ]
