# Generated by Django 4.2.5 on 2023-10-24 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.CharField(default='admin@gmail.com', max_length=122),
        ),
    ]
