# Generated by Django 4.2.5 on 2023-11-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_ticket_city_remove_ticket_monument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='monumentId',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
