# Generated by Django 4.2.5 on 2023-12-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.CharField(auto_created=True, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
