# Generated by Django 4.2.5 on 2023-12-01 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_ticket_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('email', models.CharField(max_length=255)),
                ('monumentId', models.IntegerField()),
                ('count', models.IntegerField()),
                ('price', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('shift', models.CharField(max_length=120)),
                ('scanned', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
