# Generated by Django 4.2.5 on 2023-12-01 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_token_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
